### ISSUE TITLE
'Form is online' radio button does not save when publishing (Form Builder 2.0.9)

### ISSUE THREAD

**Issue by nicktalsma** [formtools/module-form_builder#28]
Just tried upgrading from Form Builder 2.0.7 to 2.0.9. Also upgraded to the latest API and theme at the same time

Two of my dozen or so forms that were previously online where switched to offline under the publisher.  When trying to switch back to online the settings would not save. Tried several times.  

I re-uploaded the form_builder folder from the backup I made (effectively reverting back to 2.0.7) and was able to change the forms back to online, with the changes sticking.

**Comment by benkeen** [comment]
Hi @nicktalsma, I'm afraid I'm not able to reproduce this & it's really tricky to know what to suggest for debugging... hmm. 2.0.8 fixed a bug where forms were being incorrectly flagged as offline - it sounds like the problems you're experiencing are something to do with that fix. 

I don't suppose there's any way I could get access to your system to debug this? No worries if not, I do understand.

**Comment by benkeen** [comment]
For anyone reading this, we got to the bottom of it. The offline_date field in the form_builder_forms table hadn't been updated properly to allow null values. This shouldn't have been the case: upgrading should have set that value properly. I'm going to investigate this today with #30.
