### ISSUE TITLE
Placeholder options do not copy over field options when creating new template set

### ISSUE THREAD

**Issue by johnbleck3** [formtools/module-form_builder#5]
Placeholder options do not copy over field options when creating new template set.

Copying template from Conformist, the Title Font placeholder did not have any field options see attached.
![placeholders](https://user-images.githubusercontent.com/12632568/35023855-94358152-fb0a-11e7-9257-048517d5748f.png)

**Comment by benkeen** [comment]
Thanks again @johnbleck3 I'll release a new version of the module soon - so keep them bugs coming! :)
